"""updated with another attribute

Revision ID: b3825e8d2bf8
Revises: 227138c3225e
Create Date: 2022-10-27 15:34:49.289630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3825e8d2bf8'
down_revision = '227138c3225e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('solid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'solid')
    # ### end Alembic commands ###
